.TH SAC2XY 1 "20 Feb 2009" "MTINV version 2.0" "MTINV Toolkit V2.0"

.SH NAME
sac2xy

.SH SYNOPSIS
sac2xy {xreset/noxrest} {sac binary files}

.SH DESCRIPTION
Converts Seismic Analysis Code (SAC)
binary formatted files into simple ASCII text (x,y) columns.

.SH REQUIRED PARAMETERS
none

.SH OPTIONAL PARAMETERS
.TP 
.B xreset is type "Boolean"
Reset the x-values to start from 0 (default off == noxreset).

.SH "SEE ALSO"
.IR sacdata2inv (1),
.IR knet2sac (1)
