.TH UNPACK.CSH 1 "20 Feb 2009" "MTINV version 2.0" "MTINV Toolkit V2.0"

.SH NAME
unpack.csh

.SH SYNOPSIS
unpack.csh {seed file}

.SH DESCRIPTION
A C-Shell script which "unpacks" or extracts SAC binary formatted files, SAC Pole Zero instrument response files, 
and station information among other things that rdseed can extract.  

.SH REQUIRED PARAMETERS
.TP
.B seed file name

.SH "SEE ALSO"
.IR sacdata2inv (1),
.IR sacmerge (1),
.IR sacswapbytes (1),
.IR rdseed
